<a href="https://colab.research.google.com/github/kornelius-veridian/Tugas-DataMining/blob/main/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Dataset.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[['demak ' 45.0 72000.0]
 ['semarang ' 28.0 48000.0]
 ['kendal' 30.0 55000.0]
 ['demak ' 33.0 60000.0]
 ['semarang ' 47.0 nan]
 ['kendal' 31.0 58000.0]
 ['demak ' nan 52000.0]
 ['semarang ' 48.0 79000.0]
 ['kendal' 50.0 82000.0]
 ['demak ' 37.0 67000.0]]


In [4]:
print(y)

['yes' 'no' 'yes' 'yes' 'no' 'no' 'no' 'yes' 'no' 'yes']


In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [6]:
print(x)

[[1.0 0.0 0.0 45.0 72000.0]
 [0.0 0.0 1.0 28.0 48000.0]
 [0.0 1.0 0.0 30.0 55000.0]
 [1.0 0.0 0.0 33.0 60000.0]
 [0.0 0.0 1.0 47.0 nan]
 [0.0 1.0 0.0 31.0 58000.0]
 [1.0 0.0 0.0 nan 52000.0]
 [0.0 0.0 1.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 82000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [8]:
print(y)

[1 0 1 1 0 0 0 1 0 1]


In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state =1)

In [10]:
print(x_train)

[[1.0 0.0 0.0 nan 52000.0]
 [0.0 0.0 1.0 47.0 nan]
 [1.0 0.0 0.0 45.0 72000.0]
 [1.0 0.0 0.0 33.0 60000.0]
 [0.0 0.0 1.0 28.0 48000.0]
 [0.0 0.0 1.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 82000.0]
 [0.0 1.0 0.0 31.0 58000.0]]


In [11]:
print(x_test)

[[0.0 1.0 0.0 30.0 55000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [12]:
print(y_train)

[0 0 1 1 0 1 0 0]


In [13]:
print(y_test)

[1 1]


In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train [:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [15]:
print(x_train)

[[1.0 0.0 0.0 nan -1.0082256376137535]
 [0.0 0.0 1.0 0.785518367796229 nan]
 [1.0 0.0 0.0 0.5515341731335225 0.6142064229141259]
 [1.0 0.0 0.0 -0.8523709948427163 -0.3592528134026018]
 [0.0 0.0 1.0 -1.4373314814994824 -1.3327120497193294]
 [0.0 0.0 1.0 0.9025104651275822 1.1820576440988837]
 [0.0 1.0 0.0 1.1364946597902887 1.4254224531780655]
 [0.0 1.0 0.0 -1.0863551895054229 -0.5214960194553897]]
